# -*- coding: utf-8 -*-
"""Area Formulas and creating new words

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JRCsNmJeLDxPpUiDfRPYMQ0Rrm_pXrO
"""

# Problem 1
def sum_and_difference(num1, num2):
  # Calculate the sum
  sum = num1 + num2
  # Calculate the difference based on smaller and larger numbers
  if num1 > num2:
    difference = num1 - num2
  else:
    difference = num2 - num1
  
  print("Sum:")
  print(sum)
  print("Difference:")
  print(difference)

print("\nProblem #1")
number_1, number_2 = 0, 0
# Check if the input numbers are valid
while True:
  try:
    number_1 = float(input("Enter first integer number: "))
    number_2 = float(input("Enter second integer number: "))
    break
  except ValueError:
      print("Please input integer only...") 

sum_and_difference(number_1, number_2)

# Problem 2
def area_of_triangle(base, height):
  # Calculate the area of the triangle
  area = 1/2 * base * height
  
  print("Area of the triangle")
  print(area)

print("\nProblem #2")
number_1, number_2 = 0, 0
# Check if the input numbers are valid
while True:
  try:
    number_1 = float(input("Enter integer number for base: "))
    number_2 = float(input("Enter integer number for height: "))
    break
  except ValueError:
      print("Please input integer only...") 
area_of_triangle(number_1, number_2)

def check_if_word_is_valid(word):
  # Check for the avlidity of the input word
  if word is None:
    print('No word provided')
    return (False)
  elif isinstance(word, str) == False:
    print('Not a string')
    return (False)
  elif len(word) == 0:
    print('Empty string')
    return (False)
  elif word.isalpha() == False:
    print('String with non-alphabets')
    return (False)
  else:
    return True


# Problem 3
# Iterate through each letter in the string to check if it is upper or lower case and increment the counts accordingly
def count_upper_case_and_lower_case_characters(input_string):
  if check_if_word_is_valid(input_string) == True:
    upper, lower = 0, 0
    for i in input_string:
      if (i >= 'a' and i <= 'z'):
        lower = lower + 1
      elif (i >= 'A' and i <= 'Z'):
        upper = upper + 1
    
    
    print("Upper case count:")
    print(upper)
    print("Lower case count:")
    print(lower)

print("\nProblem #3")
val = input("Enter a word: ")
count_upper_case_and_lower_case_characters(val)

# Problem 4
import string
# Iterate through each letter in the word and build new words by adding suffix and prefix of subsequent letters to make different combinations
def make_new_words(start_word):
    if check_if_word_is_valid(start_word) == True:
      new_words = []
      for i, letter in enumerate(start_word):
          word_as_list = list(start_word)
          for char in string.ascii_lowercase:
              word_as_list[i] = char
              new_words.append("".join(word_as_list))

      return new_words 


print("\nProblem #4")
input_word = input("Enter a word: ")
make_new_words(input_word)