# -*- coding: utf-8 -*-
"""Dictionaries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bUiyPcx_tIPrkAIaBwZxhnyW4UEb-xKh
"""

# Problem 1
print("Problem 1:")
print("\nQuestion 1: The area code of 844 has the highest amount of numbers. This area code has 30 numbers.")
print("Question 2: The area codes of 822 and 833 have the lowest amount of numbers. These area codes have 15 numbers each.")
print("Question 3: Pages 1(A) and 11(K) would each have 13 names on them, which is the highest amount of names.")

# Problem 2
print("\nProblem 2:")
print("#1")
dictt = {'x': 1, 'y': 2, 'z': 3}
for key, value in dictt.items():
  print(value)

print("#2")
print(dictt["x"])

print("#3")
print(dictt)

print("#4")
print(len(dictt.keys()))

print("#5")
dictt.update( {'a' : 4} )
print(dictt)

print("#6")
print("Not possible because ordering/positioning is random.")

print("#7")
dictt.update( {'b' : 5} )
print(dictt)

print("#8")
del dictt["b"]
print(dictt)

print("#9")
dictt.pop("a")
print(dictt)

print("#10")
dictt["x"] = 10
print(dictt)

print("#11")
dictt.clear()
print(dictt)

print("#12")
dictt1 = {'x': 1, 'y': 2, 'z': 3}
if "x" in dictt1:
  print("Element exists")

print("#13")
copieddictt = dictt1.copy()
print(copieddictt)

print("#14")
sorteddict = sorted(dictt1)
print(sorteddict)

print("#15")
multidict = {}
multidict.setdefault("A", {})["B"] = "C"
print(multidict)