# -*- coding: utf-8 -*-
"""Graphing Sine and Cosine

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zFi8NI_qsy-B5myhhL5VEYyHQ6uMeXMz
"""

import matplotlib.pyplot as plt
import numpy as np

#create 2 subplots
fig, axs = plt.subplots(2)

# get all x and y coordinates for sin
x = [x for x in np.arange(0, 15, 0.01)]
y = [sin(x) for x in np.arange(0, 15, 0.01)]

# get all x and y coordinates for cos
x2 = [x for x in np.arange(0, 15, 0.01)]
y2 = [cos(x) for x in np.arange(0, 15, 0.01)]

# plot sin
axs[0].plot(x, y)
axs[0].axhline(0, color='black')
axs[0].title.set_text("Sine Graph")

# plot cos
axs[1].plot(x2, y2)
axs[1].axhline(0, color='black')
axs[1].title.set_text("Cosine Graph")

# display plot
fig.tight_layout()
plt.show()