# -*- coding: utf-8 -*-
"""Natural Numbers and Fibonacci

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GnrVrDKKuQ4iou3nqKjJd-F2j2vfoZ3W
"""

#Problem #1: Find the sum of first 1000 natural numbers. 
i = 0
sum = 0
#Loop through first 1000 natural numbers
for i in range(1001):
  #Add each number to the sum
  sum += i 

print("Problem 1")
print(sum)

#Problem #2: Find the sum of squares of first 1000 natural numbers.
i2 = 0
sum2 = 0
#Loop through first 1000 natural numbers
for i2 in range(1001):
  #Square each number and add it to the sum
  sum2 += i2**2

print("\nProblem 2")
print(sum2)

#Problem #3: Find the sum of cubes of first 1000 natural numbers.
i3 = 0
sum3 = 0
#Loop through first 1000 natural numbers
for i3 in range(1001):
  #Cube each number and add it to the sum
  sum3 += i3**3

print("\nProblem 3")
print(sum3)

#Problem #4: Calculate the difference of square of sum of first 1000 natural numbers and sum of squares of first 1000 natural numbers.
print("\nProblem 4")
#{(sum of first 1000 natural numbers)^2 - (sum of squares of first 1000 natural numbers)}
print((sum**2) - sum2)

#Problem #5: Calculate difference of sum of cubes of first 1000 natural numbers and square of sum of first 1000 natural numbers.
print("\nProblem 5")
#{(sum of first 1000 natural numbers)^2 - (sum of cubes of first 1000 natural numbers)}
print((sum**2) - sum3)

#Problem 6: Find the 101st Fibonacci number and the 20th even Fibonacci number
#1st Fib number
fib_1 = 1
#2nd Fib number
fib_2 = 1
#3rd Fib number
fib_3 = fib_1 + fib_2
#Count = which fib number we are at
count = 3
#calculate fib value up to 101st place
while count < 101:
  fib_1 = fib_2
  fib_2 = fib_3
  fib_3 = fib_1 + fib_2
  count += 1
#print 101st fib number
print("\nProblem 6")
print("101st fib number:")
print(fib_3)

#Print 20th even fib number
#1st Fib number
fib_1_2 = 1
#2nd Fib number
fib_2_2 = 1
#3rd Fib number
fib_3_2 = fib_1_2 + fib_2_2
#Count = which fib number we are at
count2 = 3
print("\nList of even fib numbers:")
#While fib place is under 61, 20th even number prints
while count2 < 61:
  #if the number we calculate is a multiple of 2, it is even, therefore, we print it
  if (fib_3_2 % 2 == 0):
      print(fib_3_2)
  fib_1_2 = fib_2_2
  fib_2_2 = fib_3_2
  fib_3_2 = fib_1_2 + fib_2_2
  count2 += 1

print("\nThe last number in this list is the 20th even fib number (1548008755920)")