# -*- coding: utf-8 -*-
"""Shoelace Theorem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vS703iZqz-VlYC8Pg0dgT0t39O8p_1Vv
"""

# Problem 1
def area_of_polygon_using_shoelace_theorem(vertices):
    n = len(vertices) # of corners
    area = 0.0
    for i in range(n):
        j = (i + 1) % n
        area += vertices[i][0] * vertices[j][1]
        area -= vertices[j][0] * vertices[i][1]
    area = abs(area) / 2.0
    print("The area of the polygom is: ")
    print(area)

points = [(10.0, 1.0), (0.0, 5.0), (5.0, 8.0)]
area_of_polygon_using_shoelace_theorem(points)
# Problem 2
import math

def area_of_triangle():
  base = int(input("Enter triangle base: "))
  height = int(input("Enter triangle height: "))
  area_triangle = 1/2 * base * height
  print("The area of the triangle is:")
  print(area_triangle)

def area_of_circle():
  radius = int(input("Enter cricle radius: "))
  area_circle = (math.pi * radius)**2
  print("The radius of the circle is:")
  print(area_circle)

def area_of_square():
  length_of_sides = int(input("Enter length of sides of square: "))
  area_square = length_of_sides * length_of_sides
  print("The area of the square is:")
  print(area_square)

def area_of_rhombus():
  p = int(input("Enter rhombus diagonal length 1: "))
  q = int(input("Enter rhombus diagonal length 2: "))
  area_rhombus = 1/2 * (p * q)
  print("The area of the rhombus is:")
  print(area_rhombus)

def area_of_trapezoid():
  b1 = int(input("Enter trapezoid base 1: "))
  b2 = int(input("Enter trapezoid base 2: "))
  h = int(input("Enter trapezoid height: "))
  area_trapezoid = ((b1 + b2)/2) * h
  print("The area of the trapezoid is:")
  print(area_trapezoid)

area_of_triangle()
area_of_circle()
area_of_square()
area_of_rhombus()
area_of_trapezoid()